// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANS1UdcluIq0wRNi3o_vnw9oPNRGEc060',
    appId: '1:23084953366:web:9e17d08f618dfecfb66a37',
    messagingSenderId: '23084953366',
    projectId: 'aqua-grow-497c5',
    authDomain: 'aqua-grow-497c5.firebaseapp.com',
    storageBucket: 'aqua-grow-497c5.appspot.com',
    measurementId: 'G-0QNWW736LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw9v7IEaXc29R3IuECKLHSGsBwW9P1GO0',
    appId: '1:23084953366:android:036b475294cbe121b66a37',
    messagingSenderId: '23084953366',
    projectId: 'aqua-grow-497c5',
    storageBucket: 'aqua-grow-497c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEplqubIAsRCxtfucaMWcWfwZzp47aph4',
    appId: '1:23084953366:ios:1e6acbd64a0a7b0eb66a37',
    messagingSenderId: '23084953366',
    projectId: 'aqua-grow-497c5',
    storageBucket: 'aqua-grow-497c5.appspot.com',
    iosClientId: '23084953366-16tu5lvgad6r4529l51af0ar7rkjvtfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquaGrow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEplqubIAsRCxtfucaMWcWfwZzp47aph4',
    appId: '1:23084953366:ios:c240a2cbe6c2e8f7b66a37',
    messagingSenderId: '23084953366',
    projectId: 'aqua-grow-497c5',
    storageBucket: 'aqua-grow-497c5.appspot.com',
    iosClientId: '23084953366-qparf71f7n25lianegcvqo7jlc122hnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquaGrow.RunnerTests',
  );
}
